dirs:
  - D:\E盘仓库\产能数据核算\产能基础表20210117（253
  - D:\E盘仓库\产能数据核算\替换名单（155份）
save: D:\F盘仓库\I2_production_computation\doc
wastage_from: D:\Repo\I2_production_computation2\doc\demo2_wastage\产能表-至2月17日(2).xlsx
wastage_to: D:\Repo\I2_production_computation2\doc